=== yangyiming0516/KTH_WEBProgramming_HW1/JAXB+SAX+DOM/xml/xml-resources/jaxb/CV/CV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns="http://unknown.abc/HW1/CV"
           targetNamespace="http://unknown.abc/HW1/CV">
    
     <xsd:complexType name="personname">
        <xsd:sequence>
            <xsd:element name="firstname" type="xsd:string" />
            <xsd:element name="lastname" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="Y">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1900" />
            <xsd:maxInclusive value="9999" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="M">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="12" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="D">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="31" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="simpledate">
        <xsd:sequence>
            <xsd:element name="day" type="D" />
            <xsd:element name="month" type="M" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="date">
        <xsd:complexContent>
            <xsd:extension base="simpledate">
                <xsd:sequence>
                    <xsd:element name="year" type="Y" />
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:simpleType name="personalID">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{10}"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="CV">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="fullname" type="personname" />
                <xsd:element name="ID" type="personalID" />
                <xsd:element name="selfdescription" type="xsd:string" />
                <xsd:element name="wantedplace" type="xsd:string" />
                <xsd:element name="wantedtype">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="permanent" />
                            <xsd:enumeration value="parttime" />
                            <xsd:enumeration value="contract" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== yangyiming0516/KTH_WEBProgramming_HW1/JAXB+SAX+DOM/xml/CV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:CV
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://unknown.abc/HW1/CV'
    xsi:schemaLocation='http://unknown.abc/HW1/CV ../schema/CV.xsd'>
    <fullname>
        <firstname>Harry</firstname>
        <lastname>Potter</lastname>
    </fullname>
    <ID>8007311234</ID>
    <selfdescription>I'm special</selfdescription>
    <wantedplace>Hogwarts</wantedplace>
    <wantedtype>parttime</wantedtype>

</ns1:CV>
