=== yangyiming0516/KTH_WEBProgramming_HW1/JAXB+SAX+DOM/xml/src/schema/company_info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema"
	xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">
	<element name="companyinfo">
		<complexType>
			<sequence>
				<element name="applicantname" type="string" />
				<element name="applicantage" type="int" />
				<element name="companies">
					<complexType>
						<sequence>
							<element name="company" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="headquator" type="string" />
										<element name="type" type="string" />
										<element name="numberofemployees" type="int" />
									</sequence>
									<attribute name="companyname" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== yangyiming0516/KTH_WEBProgramming_HW1/JAXB+SAX+DOM/xml/company_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:companyinfo xmlns:tns="http://unknown.abc/HW1/companyinfo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://unknown.abc/HW1/companyinfo ../schema/company_info.xsd">
	<tns:companies>
		<tns:company companyname="Google Inc.">
			<tns:headquator>Mountain View</tns:headquator>
			<tns:type>IT Technology</tns:type>
			<tns:numberofemployees>57150</tns:numberofemployees>
		</tns:company>
		<tns:company companyname="Apple Inc.">
			<tns:headquator>Cupertino</tns:headquator>
			<tns:type>IT Technology</tns:type>
			<tns:numberofemployees>115000</tns:numberofemployees>
		</tns:company>
		<tns:company companyname="JP Morgan Chase">
			<tns:headquator>New York City</tns:headquator>
			<tns:type>Finance and Banking</tns:type>
			<tns:numberofemployees>246300</tns:numberofemployees>
		</tns:company>
		<tns:company companyname="Royal Dutch Shell">
			<tns:headquator>Hague</tns:headquator>
			<tns:type>Energy and Petroleum</tns:type>
			<tns:numberofemployees>92000</tns:numberofemployees>
		</tns:company>
		<tns:company companyname="Gryffindor">
			<tns:headquator>Hogwarts</tns:headquator>
			<tns:type>Magic</tns:type>
			<tns:numberofemployees>10000</tns:numberofemployees>
		</tns:company>
		<tns:company companyname="home">
			<tns:headquator>Anywhere</tns:headquator>
			<tns:type>nothing</tns:type>
			<tns:numberofemployees>5</tns:numberofemployees>
		</tns:company>
	</tns:companies>
</tns:companyinfo>
