=== yangyiming0516/KTH_WEBProgramming_HW1/JAXB+SAX+DOM/xml/xml-resources/jaxb/Transcript/transcript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://unknown.abc/HW1/transcript" xmlns:tns="http://unknown.abc/HW1/transcript"
	elementFormDefault="qualified">
	<xsd:element name="transcripts">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="transcript" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="name" type="xsd:string" />
							<xsd:element name="university" type="xsd:string" />
							<xsd:element name="degree" type="xsd:string" />
							<xsd:element name="year">
								<xsd:simpleType>
									<xsd:restriction base="xsd:integer">
										<xsd:minInclusive value="1950" />
										<xsd:maxInclusive value="2017" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="courses">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="course" minOccurs="0"
											maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="score" type="xsd:int" />
													<xsd:element name="value" type="xsd:double" />
												</xsd:sequence>
												<xsd:attribute name="CourseName" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== yangyiming0516/KTH_WEBProgramming_HW1/java_dom_parser/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:transcripts xmlns:tns="http://unknown.abc/HW1/transcript"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://unknown.abc/HW1/transcript ../schema/transcript.xsd ">
	<tns:transcript>
		<tns:name>Jason Borne</tns:name>
		<tns:university>MIT</tns:university>
		<tns:degree>PHD in CS</tns:degree>
		<tns:year>2016</tns:year>
		<tns:courses>
			<tns:course CourseName="C++ Programming">
				<tns:score>93</tns:score>
				<tns:value>4</tns:value>
			</tns:course>
			<tns:course CourseName="Machine leaning">
				<tns:score>87</tns:score>
				<tns:value>5</tns:value>
			</tns:course>
			<tns:course CourseName="Data Structure">
				<tns:score>93</tns:score>
				<tns:value>4</tns:value>
			</tns:course>
			<tns:course CourseName="Operatin System">
				<tns:score>81</tns:score>
				<tns:value>3</tns:value>
			</tns:course>
		</tns:courses>
	</tns:transcript>

	<tns:transcript>
		<tns:name>Harry Potter</tns:name>
		<tns:university>Cambridge University</tns:university>
		<tns:degree>Master of Physics</tns:degree>
		<tns:year>2000</tns:year>
		<tns:courses>
			<tns:course CourseName="Physics">
				<tns:score>99</tns:score>
				<tns:value>6</tns:value>
			</tns:course>
			<tns:course CourseName="Experiment Principle">
				<tns:score>87</tns:score>
				<tns:value>4.5</tns:value>
			</tns:course>
			<tns:course CourseName="Rifle Shooting">
				<tns:score>100</tns:score>
				<tns:value>5.5</tns:value>
			</tns:course>
			<tns:course CourseName="Jet Piloting">
				<tns:score>100</tns:score>
				<tns:value>4.5</tns:value>
			</tns:course>
		</tns:courses>
	</tns:transcript>

</tns:transcripts>
